### ISSUE TITLE
how to compile this book?

### ISSUE THREAD

**Issue by Abhinavpatel00** [AnMnv/eBook#3]
can you please have a makefile to compile the book, the books looks awesome

**Comment by AnMnv** [comment]
Hi, thank you,  basically it should be pretty easy. You have to install full TeXLive, clone the repo and compile as any other tex file.

If you are looking for the last version of the book on the main page there is a spacial link for it -> https://docs.google.com/viewer?url=https://raw.githubusercontent.com/AnMnv/AnMnv.github.io/master/eBook.pdf

**Comment by Abhinavpatel00** [comment]
oh thanks for reply , i actually found out the mistake the problem is that you , used absolute path like start with C:/ so it makes errors while compiling on linux , may you should be using relative path

**Comment by AnMnv** [comment]
Yeah, I will rewrite the paths and make them relative in the next update + I will add a note how you can buil it + requirements and then close the issue
